name: binary-waterfall
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10*
  - pip
  - pillow
  - ffmpeg
  - pip:
    - pyinstaller
    - pyinstaller-versionfile
    - numpy
    - PyQt5
    - mutagen
    - pydub